# para versiones mas viejas de c++
CPPFLAGS=-std=c++2a

LDFLAGS=-pthread

# para versiones mas nuevas de c++
#CPPFLAGS=-std=c++20

.PHONY = all clean clase

all:  ej3 #ej1 ej2-a ej3-c
clean:
	rm -f ej1 ej2 ej3-a ej3-c
